url: https://ankilon.github.io
baseurl: 

# Site settings
title: Looking through the Iris
email: irischong1999@gmai.com
description: "Just a student with skills in stratgic analysis and a high interest in design"

# site-wide references
resume: https://drive.google.com/file/d/16HBErkf6J4I490_NW65DvQqDr7oSTgpO/view?usp=sharing



# Team names, titles and social links
people:
  


- name: Iris Chong
  pic: 4
  position: Me!
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/chongirisseon/
    - title: behance
      url: https://www.behance.net/seonchong
    - title: github
      url: https://github.com/ankilon



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: linkedin
    url: https://www.linkedin.com/in/chongirisseon/
  - title: behance
    url: https://www.behance.net/seonchong
  - title: github
    url: http://github.com/ankilon

# Postal address (add as many lines as necessary)
address:
  - line: Somewhere over the rainbow!

# Build settings
markdown: kramdown
permalink: pretty